# Generated by Django 4.2.3 on 2023-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="Дата въезда")),
                ("exit_date", models.DateField(verbose_name="Дата выезда")),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "number_of_people",
                    models.PositiveIntegerField(verbose_name="Количество людей"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("standard", "Обычный номер"),
                            ("comfort", "Комфортный номер"),
                            ("luxury", "Люкс номер"),
                        ],
                        max_length=10,
                        verbose_name="Тип номера",
                    ),
                ),
            ],
        ),
    ]
